#!/bin/bash

# Find the first available network interface
network_interface=$(ip -o -4 route show to default | awk '{print $5}')

# Set up low bandwidth using tc on the found network interface
tc qdisc add dev $network_interface root tbf rate 512kbit burst 32kbit latency 400ms

# Run the Python script
python3 gateway_publisher.py
