version: '3.8'
services:
  openfire:
    image: gizmotronic/openfire:4.4.4
    container_name: openfire
    restart: always
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
    volumes:
      - /srv/docker/openfire:/var/lib/openfire
  xmpp-sender:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./
      dockerfile: Dockerfile.sender
    volumes:
      - type: bind
        source: ./sender/csv/
        target: /app/csv/
        read_only: false
    network_mode: "host"
    depends_on:
      - openfire
      - xmpp-receiver
  xmpp-receiver:
    build: 
      context: ./
      dockerfile: Dockerfile.receiver
    volumes:
      - type: bind
        source: ./receiver/csv/
        target: /app/csv/
        read_only: false
    network_mode: "host"
    depends_on:
      - openfire
 
# ws://localhost:7070/ws/
# after first run the sender and receiver wont connect
# go to admin console at localhost:9090 and setup openfire with embeded db, domain host.docker.internal
# create two users with password 123 - goch6657@example.com , iamadit@example.com