# Use an official Node.js runtime as a base image
FROM node:lts-bullseye-slim

RUN apt-get update \
  && apt-get -y install net-tools iproute2 iperf3 \
  && apt-get clean

# Set the working directory to /app
WORKDIR /app
RUN mkdir receiver
RUN mkdir logger

COPY app/package*.json /app/

# Install the application dependencies
RUN npm install

COPY app/receiver/ /app/receiver
COPY app/logger/ /app/logger

# Define the command to run the application
CMD ["bash", "-c", "npm run receive"]