# Use an official Node.js runtime as a base image
FROM node:14

RUN apt-get update \
  && apt-get -y install net-tools iproute2 iperf3 \
  && apt-get clean

# Set the working directory to /app
WORKDIR /app

# Define the command to run the application
CMD ["npm", "start"]