version: '3.8'
networks:
  xmpp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.39.0/24
services:
  openfire:
    build: 
      context: ./
      dockerfile: Dockerfile.server
    container_name: openfire
    restart: always
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
      - "7070:7070"
    volumes:     
      - type: volume
        source: data
        target: /var/lib/openfire
    networks:
      xmpp-net:
        ipv4_address: 172.100.39.10
  xmpp-sender:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./
      dockerfile: Dockerfile.sender
    volumes:
      - type: bind
        source: ./app/csv/
        target: /app/csv/
        read_only: false
    networks:
      xmpp-net:
        ipv4_address: 172.100.39.13
    depends_on:
      - openfire
      - xmpp-receiver
  xmpp-receiver:
    build: 
      context: ./
      dockerfile: Dockerfile.receiver
    volumes:
      - type: bind
        source: ./app/csv/
        target: /app/csv/
        read_only: false
    networks:
      xmpp-net:
        ipv4_address: 172.100.39.14
    depends_on:
      - openfire
volumes:
  data:
    name: "xmpp-server-data"
 
# ws://localhost:7070/ws/
# - /srv/docker/openfire:/var/lib/openfire