version: '3.8'
services:
  openfire:
    image: sameersbn/openfire:3.10.3-19
    container_name: openfire
    restart: always
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
    volumes:
      - type: bind
        source: ./srv/docker/openfire
        target: /var/lib/openfire
        read_only: false
  xmpp-sender:
    build: 
      context: ./
      dockerfile: Dockerfile.sender
    volumes:
      - type: bind
        source: ./sender/
        target: /app/
        read_only: false
    network_mode: "host"
  xmpp-receiver:
    build: 
      context: ./
      dockerfile: Dockerfile.receiver
    volumes:
      - type: bind
        source: ./receiver/
        target: /app/
        read_only: false
    network_mode: "host"
 
# ws://localhost:7070/ws/