version: '3.8'
networks:
  mqtt-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.10.0/24
services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    user: mosquitto
    volumes:
      - type: bind
        source: ./config/
        target: /mosquitto/config/
        read_only: false
      - type: bind
        source: ./log/
        target: /mosquitto/log/
        read_only: false
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
        mqtt-net:
          ipv4_address: 172.100.10.10  
  mqtt-pub:
    build: 
      context: ./
      dockerfile: pubDockerfile
    depends_on:
      - mqtt-broker
      - mqtt-sub
      - mqtt-sub-cli
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.13
  mqtt-sub:
    build: 
      context: ./
      dockerfile: subDockerfile
    depends_on:
      - mqtt-broker
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.14
  mqtt-sub-cli:
    image: eclipse-mosquitto:latest
    command: sh -c "mosquitto_sub -h mqtt-broker -t "/device" -u admin -P password"
    depends_on:
      - mqtt-broker
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.12
volumes:
  data:
    name: "mqtt-broker-data"