version: '3.8'
networks:
  mqtt-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.10.0/24
services:
  mqtt-broker:
    build: 
      context: ./
      dockerfile: Dockerfile.broker
    user: mosquitto
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:      
      - type: bind
        source: ./log/
        target: /mosquitto/log/
        read_only: false      
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    networks:
        mqtt-net:
          ipv4_address: 172.100.10.10
  mqtt-pub:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./
      dockerfile: Dockerfile.publisher
    volumes:
      - type: bind
        source: ./log/
        target: /mosquitto/log/custom/
        read_only: false
      - type: bind
        source: ./simulation/
        target: /app/
        read_only: false
    depends_on:
      - mqtt-broker
      - mqtt-sub
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.13
  mqtt-sub:
    build: 
      context: ./
      dockerfile: Dockerfile.subscriber
    volumes:
      - type: bind
        source: ./log/
        target: /mosquitto/log/custom/
        read_only: false
      - type: bind
        source: ./simulation/
        target: /app/
        read_only: false
    depends_on:
      - mqtt-broker
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.14
volumes:
  data:
    name: "mqtt-broker-data"