version: '3.8'
networks:
  mqtt-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.10.0/24
services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    user: mosquitto
    volumes:
      - type: bind
        source: ./config/
        target: /mosquitto/config/
        read_only: false
      - type: bind
        source: ./log/
        target: /mosquitto/log/
        read_only: false
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    networks:
        mqtt-net:
          ipv4_address: 172.100.10.10
  mqtt-pub:
    build: 
      context: ./
      dockerfile: Dockerfile.publisher
    volumes:
      - type: bind
        source: ./log/
        target: /mosquitto/log/custom/
        read_only: false
      - type: bind
        source: ./simulation/
        target: /app/
        read_only: false
    depends_on:
      - mqtt-broker
      - mqtt-sub
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.13
  mqtt-sub:
    build: 
      context: ./
      dockerfile: Dockerfile.subscriber
    volumes:
      - type: bind
        source: ./log/
        target: /mosquitto/log/custom/
        read_only: false
      - type: bind
        source: ./simulation/
        target: /app/
        read_only: false
    depends_on:
      - mqtt-broker
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.14
  mqtt-sub2:
    build: 
      context: ./
      dockerfile: Dockerfile.subscriber2
    volumes:
      - type: bind
        source: ./log/
        target: /mosquitto/log/custom/
        read_only: false
      - type: bind
        source: ./simulation/
        target: /app/
        read_only: false
    depends_on:
      - mqtt-broker
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.15
volumes:
  data:
    name: "mqtt-broker-data"
    external: true